### ISSUE TITLE
Switching on V2

### ISSUE THREAD

**Issue by matthew-andrews** [Financial-Times/next-grumman#113]
Things currently not implemented on Articles V2 but available in V1:-
- [x] “See alsos” (more ons, etc) (@matthew-andrews priority this AM)
- [x] Save article (@leanne1 priority this AM)
- [ ] Metadata (related topic tags—nice to have, not essential for this week)
- [x] Recommend article (nice to have, not essential for this week)
- [ ] Advertisements (nice to have—@aintgoin2goa  offered to help, if he has time but not essential for this week)
- Time to read (not planned for Article V2 MVP)
- Inline images (not planned for Article V2 MVP—CAPI limitation, but essential for alpha)

**Comment by commuterjoy** [comment]
Can we also make sure this looks good and works  in IE9, Firefox, safari etc.
