### ISSUE TITLE
data-trackable on select boxes fires on click, not on select

### ISSUE THREAD

**Issue by commuterjoy** [Financial-Times/next-grumman#217]
http://next.ft.com/7819e8d0-be79-11e4-8036-00144feab7de

Click on the dropdown and the cta beacon fires.

So we'll get an idea of interactions but not if people are using it to navigate.

Wonder if we can track the clicks on the _option_ elements.

**Comment by ironsidevsquincy** [comment]
tracing the `option`s didn't work, not sure if it's due to the tracking code or the way the event works on options

**Comment by ironsidevsquincy** [comment]
Dropped the dropdown ui for now, so n/a
