### ISSUE TITLE
why no byline?

### ISSUE THREAD

**Issue by matthew-andrews** [Financial-Times/next-grumman#218]
http://next.ft.com/34739154-c6a2-11e4-aee8-00144feab7de

seems to have a byline & author metadata in both apis:-

v1. http://api.ft.com/content/34739154-c6a2-11e4-aee8-00144feab7de?apiKey=XXX
v2. http://api.ft.com/content/items/v1/34739154-c6a2-11e4-aee8-00144feab7de?apiKey=XXX

**Comment by matthew-andrews** [comment]
@ironsidevsquincy any idea why this is happening [comes from user feedback]

**Comment by matthew-andrews** [comment]
![screen shot 2015-03-12 at 07 01 50](https://cloud.githubusercontent.com/assets/825088/6613492/b44a676a-c885-11e4-8e06-50a56fe16da7.png)

**Comment by ironsidevsquincy** [comment]
elasticsearch response's is - https://github.com/Financial-Times/next-grumman/pull/219

**Comment by matthew-andrews** [comment]
ah that makes sense
