### ISSUE TITLE
Somethign funky happening in the title tag

### ISSUE THREAD

**Issue by matthew-andrews** [Financial-Times/next-grumman#284]
![screen shot 2015-03-20 at 11 54 59](https://cloud.githubusercontent.com/assets/825088/6751044/f92d9d84-cef7-11e4-9d1b-68d23aeca30d.png)
http://next.ft.com/11bd3a2f-975a-3d90-b6cf-e2d81fde08ff

**Comment by ironsidevsquincy** [comment]
https://github.com/Financial-Times/next-express/pull/64

**Comment by ironsidevsquincy** [comment]
Fixed
