### ISSUE TITLE
Push all images through the image service

### ISSUE THREAD

**Issue by commuterjoy** [Financial-Times/next-grumman#451]
http://next.ft.com/b6e00d9f-e07f-3ee4-86a5-f1a0d358f085

**Comment by ironsidevsquincy** [comment]
css fix - https://github.com/Financial-Times/next-grumman/pull/452

might be worth holding off until we have assets in v2

**Comment by matthew-andrews** [comment]
assets?

**Comment by matthew-andrews** [comment]
ahhh this is because that article has fallen back to capi v1…… we did already agree that when we did this we would only support plain text…… so i think we should do that……

**Comment by matthew-andrews** [comment]
OK we've sort of fixed this……… whenever we fall back to CAPI v1 for content not in V2 (in which we always put the images through the image service) we now use plain text versions.

**Comment by commuterjoy** [comment]
Great, thanks!
